### ISSUE TITLE
getSearchSelectors and reduxSearch question about resourceSelector

### ISSUE THREAD

**Issue by amelon** [treasure-data/redux-search#44]
Hello,

I can't figure out why there is a `resourceSelector` for both functions.

`resourceSelector` for `getSearchSelectors` is mandatory or does it use `reduxSeach` one by default?

In readme.md there a typo

````
const {
  text, // search text
  result // book ids
} = getSearchSelectors({
  resourceName: 'books',
  resourceSelector: (name, state) => state.resources.get(resourceName)
})
````

should be
````
const {
  text, // search text
  result // book ids
} = getSearchSelectors({
  resourceName: 'books',
  resourceSelector: (name, state) => state.resources.get(name)
})
````

**Comment by bvaughn** [comment]
Hi @amelon,

> I can't figure out why there is a `resourceSelector` for both functions.

I'm not sure I understand your question- but if I'm reading it right, you use the `text` selector returned to wire up the current value to a managed input or display your current search text perhaps. You use the `result` selector to display matching results in your view. Does this help clarify any?

Thanks for pointing out the typo in the docs. I'll update them.

**Comment by amelon** [comment]
Hello @bvaughn,
I will try to make it clearer.

In your example, you declare

````js
const enhancer = compose(
  applyMiddleware(...yourMiddleware),
  reduxSearch({
    resourceIndexes: {
      books: ['author', 'title']
    },
    resourceSelector: (resourceName, state) => {  // <- resourceSelector #1
      return state.resources.get(resourceName)
    }
  })
)
````

And then in the `connecting part`

````js
const {
  text, // search text
  result // book ids
} = getSearchSelectors({
  resourceName: 'books',
  resourceSelector: (resourceName, state) => (  // <- resourceSelector #2
    state.resources.get(resourceName)
  )
})
````

Actually, I'd like to understand usefulness of resourceSelector #2.
It is the same responsability at different time. I think  resourceSelector #2 could be optional.

**Comment by bvaughn** [comment]
Thanks for clarifying.

The way redux-search was written, [`getSearchSelectors` is just a tiny helper function](https://github.com/treasure-data/redux-search/blob/master/src/selectors.js#L16) to make creating selectors more convenient. It's not stateful (eg. it's not connected in any way to the middleware you created when you passed the result of `reduxSearch` to `compose`).

I think you're right that it would be possible to refactor the code so that the 2 factor functions shared more data. If you'd like to contribute a PR, let's chat more about what you have in mind. As for my use of the library, it's pretty trivial to pass a shared function to both redux-search factories so it's not a big deal. Something like...

```js
export function reduxSearchResourceSelector (resourceName, state) {
  return state.resources.get(resourceName)
}
```

...that is then imported and passed to both `reduxSearch(...)` and `getSearchSelectors(...)`.

**Comment by bvaughn** [comment]
I'm going to close this issue for now since it's not actionable. We can keep chatting here though. :)
